
public enum InputBindingName {
    TOGGLE_PAUSE,

    GAMEPLAY_HORIZONTAL,
    GAMEPLAY_VERTICAL,
    GAMEPLAY_ATTACK,
    GAMEPLAY_CAMHORIZONTAL,
    GAMEPLAY_CAMVERTICAL,
    GAMEPLAY_INTERACT,
    GAMEPLAY_TOGGLE_TARGETING,
    GAMEPLAY_NEXT_TARGET,
    GAMEPLAY_PRIMARY_SKILL,
    GAMEPLAY_SECONDARY_SKILL,

    PLAYER_INV_USEOREQUIP,
}
